# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' (obsolete) test if removing each site can allow to still reach the threshold with a given confidence
#' then choose randomly to remove it from the individual.
#'
#' @param viablesValues2 matrix of effects of introduction of each choice.
#' @param threshold number of sites colonised desired.
#' @param confidence matrix of effects of introduction of each choice.
#' @param viablesTriplets link between sites&time and viablesValues2.
#' @param population total population of the current generation in the evolutionnary algorithm.
#' @param pop index of the studied individual of the population
#' @param current current probabilities of presence of the species at the end of the cycles, with the unchanged individual. 
NULL

#' test if removing each site can allow to still reach the threshold with a given confidence
#' then choose the more expensive choice to remove it from the individual.
#'
#' @param viablesValues2 matrix of effects of introduction of each choice.
#' @param threshold number of sites colonised desired.
#' @param confidence matrix of effects of introduction of each choice.
#' @param viablesTriplets link between sites&time and viablesValues2.
#' @param population total population of the current generation in the evolutionnary algorithm.
#' @param pop index of the studied individual of the population
#' @param current current probabilities of presence of the species at the end of the cycles, with the unchanged individual. 
NULL

#' test if adding a site can allow to reach the threshold with a given confidence
#' then choose the less expensive choice.
#'
#' @param viablesValues2 matrix of effects of introduction of each choice.
#' @param threshold number of sites colonised desired.
#' @param confidence desired confidence of reaching a certain number of sites
#' @param viablesTriplets link between sites&time and viablesValues2.
#' @param population total population of the current generation in the evolutionnary algorithm.
#' @param pop index of the studied individual of the population
#' @param current current probabilities of presence of the species at the end of the cycles, with the unchanged individual. 
NULL

#' return the probability that the number of success of Bernouillis event with probabilities given is between
#' zero and the given threshold 
#'
#' @param probabilityVector vector of probabilities for each bernouilli event considered.
#' @param threshold1 maximum value of success tested, inclued cases with more success.
NULL

#' return the evaluation of number of success like eval_probabilitVector, with two vector summed.
#'
#' @param probabilityVector first vector
#' @param probabilityVector2 second vector
#' @param threshold1 maximum value of success tested, inclued cases with more success.
NULL

#' get a random value between 0 & (j-1)
#'
#' @param j limit-1 of random value
NULL

#' generate a permutation.
#'
#' @param  vector of probabilities for each bernouilli event considered.
#' @param threshold1 maximum value of success tested, inclued cases with more success.
NULL

#' return the special matrix product between two probability matrix. (obsolete version)
#'
#' @param A first probability matrix
#' @param B second probability matrix
NULL

#' (obsolete version) return the special matrix product between two probability matrix.
#'
#' @param A first probability matrix
#' @param B second probability matrix
NULL

#' Set the random seed for C++ 
#'
#' @param seed seed value
rcpp_set_seed <- function(seed) {
    invisible(.Call(`_IESTR_rcpp_set_seed`, seed))
}

#' return random value from ununiform probability set. 
#'
#' @param ununiform_probabilities0 Rcpp vector of probabilities for each indices value
index_random_choice_non_uniform <- function(ununiform_probabilities0) {
    .Call(`_IESTR_index_random_choice_non_uniform`, ununiform_probabilities0)
}

#' return a permutation of numbers with ununiform probabilities of being chosen.
#'
#' @param permutation_size size of the permutation
#' @param ununiform_probabilities0 relative probabilities of being chosen
generate_permutation4 <- function(permutation_size, ununiform_probabilities0) {
    .Call(`_IESTR_generate_permutation4`, permutation_size, ununiform_probabilities0)
}

#' return the special matrix product between two probability matrix.
#'
#' @param A first probability matrix
#' @param B second probability matrix
proba_matrix_mult3 <- function(A, B) {
    .Call(`_IESTR_proba_matrix_mult3`, A, B)
}

#' Establishes from the consecutiveSuitabilityMatrix what are the
#' study sites in the map and attribute them an index used in 
#' other functions.
#' Warning : the indices start at 1.
#'
#' @param consecutiveSuitabilityMatrix list of matrix of suitability for each timestep.
#' @return suitable sites as a sparse matrix
#' @export
rcpp_global_suitable_sites <- function(consecutiveSuitabilityMatrix) {
    .Call(`_IESTR_rcpp_global_suitable_sites`, consecutiveSuitabilityMatrix)
}

#' Calculate the coordinates of the suitable sites.
#'
#' @param globalSuitableSites support matrix containing index of each sites
#' @return coordinates of the suitable sites as a matrix
#' @export
rcpp_global_suitable_coordinates <- function(globalSuitableSites) {
    .Call(`_IESTR_rcpp_global_suitable_coordinates`, globalSuitableSites)
}

#' Calculate the spread_matrix
#'
#' @param Eigen::SparseMatrix<double> globalSuitableSites support matrix containing index of each sites
#' @param Rcpp::NumericMatrix globalSuitableCoordinates support matrix coordinates of each sites
#' @param Rcpp::NumericMatrix migrationKernel matrix modelling spread properties of the species.
#' @return Spread matrix used to model spread behavior of the species without suitability
#' @export
rcpp_spread_matrix <- function(globalSuitableSites, globalSuitableCoordinates, migrationKernel) {
    .Call(`_IESTR_rcpp_spread_matrix`, globalSuitableSites, globalSuitableCoordinates, migrationKernel)
}

#' Calculate the local transition matrices from the spread matrix and suitability matrices
#'
#' @param std::list<Eigen::SparseMatrix<double>> consecutiveSuitabilityMatrix list of suitability matrix
#' @param Eigen::SparseMatrix<double> spreadmatrix matrix used to model spread behavior of the species without suitability
#' @param Rcpp::NumericMatrix globalSuitableCoordinates support matrix coordinates of each sites
#' @return list of matrix used to model spread behavior of the species with suitability, between two adjacent timestep
#' @export
rcpp_local_transition_matrix <- function(consecutiveSuitabilityMatrix, spreadmatrix, globalSuitableCoordinates) {
    .Call(`_IESTR_rcpp_local_transition_matrix`, consecutiveSuitabilityMatrix, spreadmatrix, globalSuitableCoordinates)
}

#' Calculate the transition matrices from the local transition matrices
#'
#' @param std::list<Eigen::SparseMatrix<double>> list of matrix used to model spread behavior of the species with suitability, between two adjacent timestep
#' @return list of transition matrices from any timestep to the last timestep.
#' @export
rcpp_transition_matrix <- function(localtransitionmatrices) {
    .Call(`_IESTR_rcpp_transition_matrix`, localtransitionmatrices)
}

#' Calculate sites&times introduction considered "viable" 
#' eg that are not totally bested by other timings of introduction for the same site, 
#' and that are efficient enough. (colonises more than one site on average).
#'
#' @param Eigen::SparseMatrix<double>> transitionmatrices list of transition matrices from any timestep to the last timestep.
#' @return boolean sparse matrix, each row correspond to a time, each column to a site. (1=viable; 0=not viable)
#' @export
rcpp_viable_sites <- function(transitionmatrices) {
    .Call(`_IESTR_rcpp_viable_sites`, transitionmatrices)
}

#' Returns matrix summing up information of each viable site&time pair.
#'
#' @param Eigen::SparseMatrix<double> viableSites boolean sparse matrix, each row correspond to a time, each column to a site. (1=viable; 0=not viable)
#' @param std::list<Eigen::SparseMatrix<double>> transitionmatrices list of transition matrices from any timestep to the last timestep.
#' @param Rcpp::NumericMatrix globalSuitableCoordinates support matrix coordinates of each sites
#' @param Eigen::SparseMatrix<double> globalSuitableSites support matrix containing index of each sites
#' @param Eigen::SparseMatrix<double> costMatrix matrix of cost of introduction
#' @return For each viable site : index, position on map, time, and cost.
#' @export
rcpp_viable_triplets <- function(viableSites, transitionmatrices, globalSuitableCoordinates, globalSuitableSites, costMatrix) {
    .Call(`_IESTR_rcpp_viable_triplets`, viableSites, transitionmatrices, globalSuitableCoordinates, globalSuitableSites, costMatrix)
}

#' Summing up the effect on the final state of the system of each viable site&time pair.
#'
#' @param Rcpp::NumericMatrix viablesTriplets For each viable site : index, position on map, time, and cost.
#' @param Eigen::SparseMatrix<double> viableSites boolean sparse matrix, each row correspond to a time, each column to a site. (1=viable; 0=not viable)
#' @param Eigen::SparseMatrix<double> globalSuitableSites support matrix containing index of each sites
#' @param std::vector<Eigen::SparseMatrix<double>> transitionmatrices list of transition matrices from any timestep to the last timestep.
#' @return for each viable site : index, position on map, time, and cost.
#' @export
rcpp_viable_values <- function(viablesTriplets, viableSites, globalSuitableSites, transitionmatrices) {
    .Call(`_IESTR_rcpp_viable_values`, viablesTriplets, viableSites, globalSuitableSites, transitionmatrices)
}

#' Evaluate how would evolve the current present species without introduction.
#'
#' @param threshold number of site with presence we want to obtain.
#' @param Eigen::SparseMatrix<double> currentPresenceMatrix matrix of presence of the species.
#' @param std::vector<Eigen::SparseMatrix<double>> transitionmatrices list of transition matrices from any timestep to the last timestep.
#' @param Eigen::SparseMatrix<double> globalSuitableSites support matrix containing index of each sites
#' @return for each viable site : index, position on map, time, and cost.
#' @export
rcpp_eval_current_prob <- function(threshold, currentPresenceMatrix, transitionmatrices, globalSuitableSites) {
    .Call(`_IESTR_rcpp_eval_current_prob`, threshold, currentPresenceMatrix, transitionmatrices, globalSuitableSites)
}

#' Evaluate the potential of each site&time pair, and give them weights for the optimization algorithm.
#'
#' @param Rcpp::NumericMatrix viablesTriplets information about each of the viable site&time pair.
#' @return a pre-ranking of each site&time pair for the algorithm.
#' @export
rcpp_pheromons <- function(viablesTriplets) {
    .Call(`_IESTR_rcpp_pheromons`, viablesTriplets)
}

#' Genrate initial population for the genetic algorithm.
#'
#' @param Rcpp::NumericVector pheromons weights of relative importance of each site&time pair.
#' @param Eigen::SparseMatrix<double> globalSuitableSites support matrix containing index of each sites
#' @param int npop number of individuals in the initial population
#' @param int nbtoplant pre-evaluate number of introduction necessary (overestimated, usually)
#' @return an initial population of set of site&time choices of introduction
#' @export
rcpp_generate_population <- function(pheromons, globalSuitableSites, npop, nbtoplant) {
    .Call(`_IESTR_rcpp_generate_population`, pheromons, globalSuitableSites, npop, nbtoplant)
}

#' Genetic algorithm used to optimised choices of introduction under the constraint of reaching a dertain number of 
#' presence at the end of the study period (threshold) with a minimal probability (confidence) while miimizing the cost
#' of all the introductions
#'
#' @param Rcpp::NumericVector pheromons weights of relative importance of each site&time pair.
#' @param Rcpp::NumericMatrix viablesTriplets For each viable site : index, position on map, time, and cost.
#' @param Rcpp::NumericMatrix population0 An initial population of set of site&time choices of introduction
#' @param Eigen::SparseMatrix<double> costMatrix matrix of costs of introduction, sparse.
#' @param Eigen::SparseMatrix<double> currentPresenceMatrix matrix of current presence of the species, sparse.
#' @param std::vector<Eigen::SparseMatrix<double>> transitionmatriceslist of transition matrices from any timestep to the last timestep.
#' @param Eigen::SparseMatrix<double> globalSuitableSites matrix of viable sites to use for the optimiation part.
#' @param Eigen::SparseMatrix<double> viablesValues viables values from transitions matrices from viable sites.
#' @param int threshold number of presence site to reach at the end of the studied period, with the introductions
#' @param double confidence minimal probability to reach the threshold accepted by the optimisation algorithm 
#' @param int npop genetic algorithm : size of the population
#' @param int nsur genetic algorithm : size of the surviving population
#' @param int ngen genetic algorithm : number of generation
#' @return an optimised population matrix of set of site&time choices of introduction.
#' @export
rcpp_algorithm_opt <- function(pheromons, viablesTriplets, population0, costMatrix, currentPresenceMatrix, transitionmatrices, globalSuitableSites, viablesValues, threshold, confidence, npop, nsur, ngen, nbtoplant) {
    .Call(`_IESTR_rcpp_algorithm_opt`, pheromons, viablesTriplets, population0, costMatrix, currentPresenceMatrix, transitionmatrices, globalSuitableSites, viablesValues, threshold, confidence, npop, nsur, ngen, nbtoplant)
}

#' Rewriting the final population given by the genetic algorithm with coordinates and times of introduction
#'
#' @param Rcpp::NumericMatrix lastPopulation a matrix of an optimised population obtain with the genetic algorithm
#' @param Rcpp::NumericMatrix viablesTriplets a matrix of information about each viable site.
#' @return the choices of introduction in coordinates and timesteps.
#' @export
rcpp_result_to_choice <- function(lastPopulation, viablesTriplets) {
    .Call(`_IESTR_rcpp_result_to_choice`, lastPopulation, viablesTriplets)
}

