# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

optgenam3 <- function(currentPresenceMatrix, consecutiveSuitabilityMatrix, costMatrix, migrationKernel, threshold, confidence, npop, nsur, ngen) {
    .Call(`_IESTR_optgenam3`, currentPresenceMatrix, consecutiveSuitabilityMatrix, costMatrix, migrationKernel, threshold, confidence, npop, nsur, ngen)
}

rcpp_set_seed <- function(seed) {
    invisible(.Call(`_IESTR_rcpp_set_seed`, seed))
}

index_random_choice_non_uniform <- function(ununiform_probabilities0) {
    .Call(`_IESTR_index_random_choice_non_uniform`, ununiform_probabilities0)
}

generate_permutation4 <- function(permutation_size, ununiform_probabilities0) {
    .Call(`_IESTR_generate_permutation4`, permutation_size, ununiform_probabilities0)
}

proba_matrix_mult3 <- function(A, B) {
    .Call(`_IESTR_proba_matrix_mult3`, A, B)
}

#' Establishes from the consecutiveSuitabilityMatrix what are the
#' study sites in the map and attribute them an index used in 
#' other functions.
#' Warning : the indices start at 1.
#'
#' @param std::list<Eigen::SparseMatrix<double>> consecutiveSuitabilityMatrix
#' @return suitable sites as a sparse matrix
rcpp_global_suitable_sites <- function(consecutiveSuitabilityMatrix) {
    .Call(`_IESTR_rcpp_global_suitable_sites`, consecutiveSuitabilityMatrix)
}

#' Calculate the coordinates of the suitable sites.
#'
#' @param Eigen::SparseMatrix<double> globalSuitableSites
#' @return coordinates of the suitable sites as a matrix
rcpp_global_suitable_coordinates <- function(globalSuitableSites) {
    .Call(`_IESTR_rcpp_global_suitable_coordinates`, globalSuitableSites)
}

#' Calculate the spread_matrix
#'
#' @param Eigen::SparseMatrix<double> globalSuitableSites
#' @param Rcpp::NumericMatrix globalSuitableCoordinates
#' @param Rcpp::NumericMatrix migrationKernel
#' @return Product of v1 and v2
rcpp_spread_matrix <- function(globalSuitableSites, globalSuitableCoordinates, migrationKernel) {
    .Call(`_IESTR_rcpp_spread_matrix`, globalSuitableSites, globalSuitableCoordinates, migrationKernel)
}

#' Multiplies two doubles
#'
#' @param std::list<Eigen::SparseMatrix<double>> consecutiveSuitabilityMatrix
#' @param Eigen::SparseMatrix<double> localTransitionMatrix
#' @param Rcpp::NumericMatrix globalSuitableCoordinates
#' @return Product of v1 and v2
rcpp_local_transition_matrix <- function(consecutiveSuitabilityMatrix, localTransitionMatrix, globalSuitableCoordinates) {
    .Call(`_IESTR_rcpp_local_transition_matrix`, consecutiveSuitabilityMatrix, localTransitionMatrix, globalSuitableCoordinates)
}

rcpp_transition_matrix <- function(transitionMatrices) {
    .Call(`_IESTR_rcpp_transition_matrix`, transitionMatrices)
}

rcpp_viable_sites <- function(colonisationMatrices) {
    .Call(`_IESTR_rcpp_viable_sites`, colonisationMatrices)
}

rcpp_viable_triplets <- function(viableSites, colonisationMatrices, globalSuitableCoordinates, globalSuitableSites, costMatrix) {
    .Call(`_IESTR_rcpp_viable_triplets`, viableSites, colonisationMatrices, globalSuitableCoordinates, globalSuitableSites, costMatrix)
}

rcpp_viable_values <- function(viablesTriplets, viableSites, globalSuitableSites, colonisationMatrices) {
    .Call(`_IESTR_rcpp_viable_values`, viablesTriplets, viableSites, globalSuitableSites, colonisationMatrices)
}

rcpp_eval_current_prob <- function(threshold, currentPresenceMatrix, colonisationMatrices, globalSuitableSites) {
    .Call(`_IESTR_rcpp_eval_current_prob`, threshold, currentPresenceMatrix, colonisationMatrices, globalSuitableSites)
}

rcpp_pheromons <- function(viablesTriplets) {
    .Call(`_IESTR_rcpp_pheromons`, viablesTriplets)
}

rcpp_generate_population <- function(pheromons, globalSuitableSites, npop, nbtoplant) {
    .Call(`_IESTR_rcpp_generate_population`, pheromons, globalSuitableSites, npop, nbtoplant)
}

rcpp_algorithm_opt <- function(pheromons, viablesTriplets, population0, costMatrix, currentPresenceMatrix, colonisationMatrices, globalSuitableSites, viablesValues, threshold, confidence, npop, nsur, ngen, nbtoplant) {
    .Call(`_IESTR_rcpp_algorithm_opt`, pheromons, viablesTriplets, population0, costMatrix, currentPresenceMatrix, colonisationMatrices, globalSuitableSites, viablesValues, threshold, confidence, npop, nsur, ngen, nbtoplant)
}

rcpp_result_to_choice <- function(lastPopulation, viablesTriplets) {
    .Call(`_IESTR_rcpp_result_to_choice`, lastPopulation, viablesTriplets)
}

